nelmio_api_doc:
    documentation:
        info:
            title: Documentation de l'API BileMo
            description: Jeux de données BileMo (produits + utilisateurs liés au client)
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
