nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        servers:
            - url: https://127.0.0.1:8000/
              description: API over HTTPS
            - url: http://127.0.0.1:8000/
              description: API over HTTP
        info:
            title: API Bilemo
            description: Jeux de données BileMo (produits + utilisateurs liés au client)
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
