nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        servers:
            - url: https://127.0.0.1:8000/
              description: API over HTTPS
        info:
            title: API Bilemo
            description: Jeux de données BileMo (produits + utilisateurs liés au client)
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    summary: get jwt
                    parameters:
                        - in: path
                          name: user
                          description: user credentials
                          schema:
                              type: object
                              required:
                                  - userName
                              properties:
                                  username:
                                      type: string
                                  password:
                                      type: string
