#index:
#    path: /
#    controller: App\Controller\DefaultController::index

products:
  path: /api/products
  controller: App\Controller\ApiProductController::list

product_detail:
  path: /api/products/{id}
  controller: App\Controller\ApiProductController::show

users:
  path: /api/customers/{id}
  controller: App\Controller\ApiCustomerController::list

user_detail:
  path: /api/customers/users/{id}
  controller: App\Controller\ApiCustomerController::show