#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /api/login_check

products:
  path: /api/products
  controller: App\Controller\ApiProductController::list

product_detail:
  path: /api/products/{id}
  controller: App\Controller\ApiProductController::show

users:
  path: /api/users
  controller: App\Controller\ApiUserController::list

user_detail:
  path: /api/users/{id}
  controller: App\Controller\ApiUserController::show

user_create:
  path: /api/users
  controller: App\Controller\ApiUserController::create

user_delete:
  path: /api/users/{id}
  controller: App\Controller\ApiUserController::delete

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
